[Icon Theme]
Name=Vanilla Box Icons Dark
Comment=A minimal, modern look — dark variant
Inherits=breeze-dark,breeze,hicolor
Example=start-here-kde
Directories=actions/scalable,apps/scalable,categories/scalable,devices/scalable,places/scalable,status/scalable

[actions/scalable]
Size=22
MinSize=8
MaxSize=512
Context=Actions
Type=Scalable

[apps/scalable]
Size=22
MinSize=8
MaxSize=512
Context=Applications
Type=Scalable

[categories/scalable]
Size=22
MinSize=8
MaxSize=512
Context=Categories
Type=Scalable

[devices/scalable]
Size=22
MinSize=8
MaxSize=512
Context=Devices
Type=Scalable

[places/scalable]
Size=22
MinSize=8
MaxSize=512
Context=Places
Type=Scalable

[status/scalable]
Size=22
MinSize=8
MaxSize=512
Context=Status
Type=Scalable
